# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 14:48
from __future__ import unicode_literals

from django.db import migrations


def replace_null_with_empty_strings(apps, schema_editor):
    TaskStatus = apps.get_model('taskmonitor', 'TaskStatus')
    TaskStatus.objects.filter(task_id=None).update(task_id='')


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('taskmonitor', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(replace_null_with_empty_strings, do_nothing),
    ]
