# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmonitor', '0002_auto_20180927_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='task_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
    ]
