# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-18 07:59
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0008_auto_20180822_1308'),
        ('email', '0043_auto_20180906_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDraftMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None, verbose_name='to')),
                ('cc', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None, verbose_name='cc')),
                ('bcc', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None, verbose_name='bcc')),
                ('headers', models.TextField(blank=True, null=True, verbose_name='email headers')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='subject')),
                ('body', models.TextField(blank=True, null=True, verbose_name='html body')),
                ('mapped_attachments', models.IntegerField(verbose_name='number of mapped attachments')),
                ('original_attachment_ids', models.TextField(default=b'', validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('template_attachment_ids', models.CharField(default=b'', max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('original_message_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('send_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_messages', to='email.EmailAccount', verbose_name='from')),
                ('tenant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.Tenant')),
            ],
            options={
                'verbose_name': 'email draft message',
                'verbose_name_plural': 'email draft messages',
            },
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='received_by_bcc',
            field=models.ManyToManyField(related_name='received_messages_as_bcc', to='email.Recipient'),
        ),
    ]
