# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-19 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0044_auto_20181018_0759'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailDraftMessage',
            new_name='EmailDraft',
        ),
    ]
